import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import theme from "tailwindcss/defaultTheme";
import {ThemeProvider} from "@/components/theme-provider";
import {SidebarNav} from "@/components/nav";
import {Separator} from "@/components/ui/separator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const sidebarNavItems = [
  {
    title: "New Application",
    href: "/",
  },
  {
    title: "View Instances",
    href: "/view-instances",
  },
  {
    title: "Logs",
    href: "/internal-logs",
  },
  {
    title: "Backend Control",
    href: "/backend-control",
  },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>
      <div className="hidden space-y-6 p-10 pb-16 md:block">
        <div className="space-y-0.5">
          <h2 className="text-2xl font-bold tracking-tight">Aspire Internal</h2>
        </div>
        <Separator className="my-6"/>
        <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
          <aside className="-mx-4 lg:w-1/5">
            <SidebarNav items={sidebarNavItems}/>
          </aside>
          <Separator className="h-[calc(100vh-185px)]" orientation="vertical"/>
          <div className="flex-1">
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </div>
        </div>
      </div>
    </body>
    </html>
  );
}
