import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/theme-provider";
import {SidebarNav} from "@/components/nav";
import {Separator} from "@/components/ui/separator";
import {UserPlus2, ServerIcon, LogsIcon, Settings2Icon} from "lucide-react";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

    <body className={inter.className}>
      <div className="hidden md:block">
        <div className="p-2 pl-6 bg-muted/50">
          <h2 className="scroll-m-20 text-2xl font-semibold tracking-tight">Aspire Internal</h2>
        </div>
        <Separator/>
        <div className="flex flex-col lg:flex-row">
          <aside className="lg:w-[200px] p-2 bg-muted/50 flex flex-col lg:flex-row">
            <SidebarNav />
          </aside>
          <Separator className="lg:h-[calc(100vh-50px)]" orientation="vertical"/>
          <div className="flex-1 p-5">
            <ThemeProvider
                attribute="class"
                defaultTheme="dark"
                enableSystem
                disableTransitionOnChange
            >
              {children}
              <Toaster />
            </ThemeProvider>
          </div>
        </div>
      </div>
    </body>
    </html>
  );
}
